{{- if .Values.backend.auth.apiKeys }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backend.auth.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bifrost.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.backend.auth.secretKey }}: {{ .Values.backend.auth.apiKeys | quote }}
{{- end }}
