apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bifrost.fullname" . }}-backend
  labels:
    {{- include "bifrost.labels" . | nindent 4 }}
data:
  {{ .Values.backend.teams.apiTokenSecretKey }}: {{ .Values.backend.teams.apiToken | required }}