apiVersion: v1
kind: Service
metadata:
  name: {{ include "bifrost.fullname" . }}-backend
  labels:
    {{- include "bifrost.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "bifrost.selectorLabels" . | nindent 4 }}
    component: backend
