{{- if and .Values.networkPolicy .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-backend
spec:
  egress:
  - to:
    - ipBlock:
        cidr: {{ .Values.networkPolicy.apiServerCIDR | required "networkPolicy.apiServerCIDR is required" }}
  {{- if .Values.networkPolicy.allowDNS }}
  - to:
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          k8s-app: node-local-dns
    ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
  # GitHub API
  - to:
    - ipBlock:
        cidr: 140.82.121.5/32
    - ipBlock:
        cidr: 140.82.121.6/32
    ports:
    - port: 443
      protocol: TCP
   u
  {{- end }}
  podSelector:
    matchLabels:
      {{- include "bifrost.selectorLabels" . | nindent 6 }}
      component: backend
  policyTypes:
  - Egress
{{- end }}
