apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "bifrost.name" . }}-unleash-admin
  namespace: {{ .Values.backend.unleash.instanceNamespace }}
  labels:
    {{- include "bifrost.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "bifrost.name" . }}-unleash-admin
subjects:
  - kind: ServiceAccount
    name: {{ include "bifrost.name" . }}
    namespace: {{ .Release.Namespace }}
