apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bifrost.name" . }}
  labels:
    {{- include "bifrost.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.backend.google.serviceAccountEmail }}
