apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "bifrost.name" . }}-unleash-admin
  namespace: {{ .Values.backend.unleash.instanceNamespace }}
  labels:
    {{- include "bifrost.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - secrets/status
      - events
      - pods
      - pods/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - unleash.nais.io
    resources:
      - unleashes
    verbs:
      - "*"
  - apiGroups:
      - networking.gke.io
    resources:
      - fqdnnetworkpolicies
    verbs:
      - "*"
