apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bifrost.fullname" . }}-backend
  labels:
    {{- include "bifrost.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.backend.teams.apiTokenSecretKey }}: {{ .Values.backend.teams.apiToken | required ".teams.apiToken can not be empty" }}