apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ .Release.Name }}-alerts
spec:
  groups:
    - name: unleash_database_alerts
      rules:
      - alert: UnleashHighDatabaseLatency
        expr: sum(db_query_duration_seconds{quantile="0.99", namespace="{{ .Values.backend.unleash.instanceNamespace }}"}) by (service) > 0.5
        for: 5m
        labels:
          severity: warning
          namespace: {{ .Release.Namespace }}
        annotations:
          summary: |
            {{ "The p99 database query latency for Unleash instance `{{ $labels.service }}` has been above 0.5 seconds for the last 5 minutes." }}
          consequence: "Applications may experience slow response times from Unleash API and UI."
          action: |
            {{ "Check the database for slow queries and add indexes where appropriate." }}
    - name: unleash_http_alerts
      rules:
      - alert: UnleashUnsuccessfulRequests
        expr: sum(rate(nginx_ingress_controller_requests{namespace="{{ .Values.backend.unleash.instanceNamespace }}", status=~"5.."}[5m])) / sum(rate(nginx_ingress_controller_requests{namespace="{{ .Values.backend.unleash.instanceNamespace }}"}[5m])) > 0.05
        for: 5m
        labels:
          severity: warning
          namespace: {{ .Release.Namespace }}
        annotations:
          summary: "High rate of unsuccessful requests for Nginx Ingress Controller"
          consequence: "Applications may problems fetching feature toggles from Unleash or taking actions in the Unleash UI."
          action: "Check the Nginx Ingress Controller logs request endpoints for errors and investigate the root cause of the issue."
    - name: unleasherator_alerts
      rules:
      - alert: UnleasheratorConnectionProblem
        expr: unleasherator_unleash_status{status="Connected"} == 0
        for: 5m
        labels:
          severity: critical
          namespace: {{ .Release.Namespace }}
        annotations:
          summary: "No connected instances for Unleash"
          consequence: "Unleasherator is not able to connect to Unleash and create new API keys for applications."
          action: "Check the Unleasherator logs for errors and investigate the root cause of the issue."
