apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ .Release.Name }}-alerts
spec:
  groups:
    - name: unleash_database_alerts
      rules:
      - alert: UnleashHighDatabaseLatency
        expr: sum(db_query_duration_seconds{quantile="0.99", namespace="{{ .Values.backend.unleash.instanceNamespace }}"}) by (service) > 0.5
        for: 5m
        labels:
          severity: warning
          labels:
            namespace: {{ .Release.Namespace }}
            severity: warning
        annotations:
          summary: |
            {{ "The p99 database query latency for Unleash instance `{{ $labels.service }}` has been above 0.5 seconds for the last 5 minutes." }}
          consequence: "Applications may experience slow response times from Unleash API and UI."
          actions: |
            {{ "Check the database for slow queries and add indexes where appropriate." }}
    - name: unleash_http_alerts
      rules:
      - alert: UnleashUnsuccessfulRequests
        expr: sum(rate(nginx_ingress_controller_requests{namespace="{{ .Values.backend.unleash.instanceNamespace }}", status=~"5.."}[5m])) / sum(rate(nginx_ingress_controller_requests{namespace="{{ .Values.backend.unleash.instanceNamespace }}"}[5m])) > 0.05
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High rate of unsuccessful requests for Nginx Ingress Controller"
          description: "The rate of unsuccessful requests for Nginx Ingress Controller in the bifrost-unleash namespace has been above 5% of the total request rate for the last 5 minutes."
          actions: "Check the Nginx Ingress Controller logs for errors and investigate the root cause of the issue."
    - name: unleasherator_alerts
      rules:
      - alert: UnleasheratorConnectionProblem
        expr: unleasherator_unleash_status{status="Connected"} == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "No connected instances for Unleash"
          description: "The Unleash operator is not able to connect to any Unleash service instances."
          actions: "Check the Unleash operator logs for errors and investigate the root cause of the issue."
