apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backend.unleash.teamsApiTokenSecretName }}
  namespace: {{ .Values.backend.unleash.instanceNamespace }}
  labels:
    {{- include "bifrost.labels" . | nindent 4 }}
data:
  {{ .Values.backend.unleash.teamsApiTokenSecretKey }}: {{ .Values.backend.unleash.teamsApiToken | required "unleash.teamsApiToken can not be empty" }}