apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.backend.unleash.kubernetesServiceAccountName }}
  namespace: {{ .Values.backend.unleash.instanceNamespace }}
  labels:
    {{- include "bifrost.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.backend.unleash.googleServiceAccountEmail }}
