linters-settings:
  staticcheck:
    checks:
      - "all"
      - "-SA1019" # Disable deprecation warnings - we intentionally use deprecated fields for backwards compatibility
      - "-ST1005" # Disable capitalized error string check - generated code from oapi-codegen violates this

issues:
  exclude-rules:
    # Allow using deprecated fields in handlers (CustomVersion, AllowedNamespaces are deprecated but still supported)
    - path: pkg/api/http/v1/handlers/unleash\.go
      linters:
        - staticcheck
      text: "SA1019"

    # Exclude generated OpenAPI code from all linting checks
    - path: pkg/api/generated/
      linters:
        - staticcheck
        - golint
        - stylecheck
