name: Build and Deploy

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write

jobs:
  build-and-deploy:
    uses: nais/actions/.github/workflows/mise-build-deploy-fasit.yaml@e6eeb636a4e6274711288cbec3c22f43a3db8600 # ratchet:nais/actions/.github/workflows/mise-build-deploy-fasit.yaml@main
    secrets:
      NAIS_IO_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}
    with:
      mise-tasks: ${{ github.event_name == 'pull_request' && '["tidy-check", "fmt-check", "generate-check", "lint", "vet", "check", "test"]' || '["tidy-check", "fmt-check", "generate-check", "lint", "vet", "check", "test-race"]' }}
      builds-docker: true
      builds-chart: true
      creates-git-tag: true

  deploy:
    name: Deploy
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build-and-deploy
    runs-on: fasit-deploy
    permissions:
      id-token: write
    steps:
      - uses: nais/fasit-deploy@58a70a338b16dc646373c91724fc7e7522d085a4 # ratchet:nais/fasit-deploy@v4.0.1
        with:
          chart: oci://europe-north1-docker.pkg.dev/nais-io/nais/charts/${{ needs.build-and-deploy.outputs.name }}
          version: ${{ needs.build-and-deploy.outputs.version }}
          targets: |
            [
              { "target": { "kind": "management", "tenant": "ci-nais" }, "wait": true },
              { "target": { "kind": "management", "tenant": "dev-nais" } }
            ]
